security:
    hash: 63154c7814aeb3b2fb2ce06e583556b01a581655ae8f492182d13f4721f04440
    whitelist:
        - 127.0.0.1
    blacklist:
        file: 'blacklist.yml'

twig: 
    path: 'resources/views'
    env:
        debug: true
        
user:
    expire: 2
plugins:
    -
        name: aceeditor
        class: '\Turp\Plugin\Aceeditor'
        routes: '/resources/config/routing.yml'