_home:
    path: /
    defaults: { controller: TurpEdit\Common\Uri::actionHome, auth: true }

_ajax:
    path: /ajax/
    defaults: { controller: TurpEdit\Common\Uri::actionAjax, auth: true }
    
_settings:
    path: /settings/
    defaults: { controller: TurpEdit\Common\Uri::actionSettings, auth: true }    
    
_login:
    path: /login/
    defaults: { controller: TurpEdit\Common\Uri::actionLogin, auth: false }

_logout:
    path: /logout/
    defaults: { controller: TurpEdit\Common\Uri::actionLogout, auth: false }
    
_settings:
    path: /project/
    defaults: { controller: TurpEdit\Common\Uri::actionProject, auth: false }  


